
--    private long id;
--    private User orderUser;
--    private Room room;
--    private Date dateFrom;
--    private Date dateTo;
--    private double moneyPaid;

CREATE TABLE ORDERS(
ORDERS_ID NUMBER,
CONSTRAINT ORDERS_PK PRIMARY KEY(ORDERS_ID),
USERS_ID NUMBER NOT NULL,
CONSTRAINT USERS_FK FOREIGN KEY (USERS_ID) REFERENCES USERS(USERS_ID),
ROOM_ID NUMBER NOT NULL,
CONSTRAINT ROOM_FK FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID),
DATE_FROM TIMESTAMP,
DATE_TO TIMESTAMP,
MONEY_PAID NUMBER (10,2) NOT NULL
);
