
CREATE SEQUENCE HOTEL_SEQ INCREMENT BY 1 MAXVALUE 1000 CYCLE;
DROP SEQUENCE HOTEL_SEQ;


CREATE SEQUENCE ORDERS_SEQ INCREMENT BY 1 MAXVALUE 1000 CYCLE;
DROP SEQUENCE ORDERS_SEQ;


CREATE SEQUENCE ROOM_SEQ INCREMENT BY 1 MAXVALUE 1000 CYCLE;
DROP SEQUENCE ROOM_SEQ;


CREATE SEQUENCE USERS_SEQ INCREMENT BY 1 MAXVALUE 1000 CYCLE;
DROP SEQUENCE USERS_SEQ;

