
--    private long id;
--    private String userName;
--    private String password;
--    private String country;
--    private UserType userType;
--    private List orders;

CREATE TABLE USERS(
USERS_ID NUMBER,
CONSTRAINT USERS_PK PRIMARY KEY(USERS_ID),
USER_NAME NVARCHAR2(50) NOT NULL,
USER_PASS NVARCHAR2(50) NOT NULL,
USER_COUNTRY NVARCHAR2(50) NOT NULL,
USER_TYPE NVARCHAR2(5) DEFAULT 'USER' NOT NULL,
CHECK (USER_TYPE = 'ADMIN' OR USER_TYPE = 'USER')
);

--CHECK (USER_TYPE BETWEEN 'ADMIN' AND 'USER')
--CHECK (USER_TYPE = 'ADMIN' OR USER_TYPE = 'USER')
