CREATE TABLE ORDERS(
ID NUMBER,
CONSTRAINT ORDER_ID PRIMARY KEY (ID),
PRODUCT_NAME NVARCHAR2(20),
PRICE NUMBER,
DATE_ORDERED TIMESTAMP,
DATE_CONFIRMED TIMESTAMP
);

INSERT INTO PRODUCT VALUES (1005, 'test5', 'qqqwewee', 500);
INSERT INTO PRODUCT VALUES (1001, 'test1', 'qqqwewee', 100);
INSERT INTO PRODUCT VALUES (1002, 'test2', 'qqqwewee', 120);
INSERT INTO PRODUCT VALUES (1003, 'test3', 'qqqwewee', 200);
INSERT INTO PRODUCT VALUES (1004, 'test4', 'qqqwewee', 130);