--INSERT
INSERT INTO PRODUCT VALUES (1001, 'test1', 'dfregjhbhb   eruhbvqre', 100);
INSERT INTO PRODUCT VALUES (1002, 'test2', 'kefbwekjbf   KERHEJFBJWKEB', 200);
INSERT INTO PRODUCT VALUES (1003, 'test3', 'kjfbejbfnw;elnf;lenflk<nf', 300);
INSERT INTO PRODUCT VALUES (1004, 'test4', 'qwhdLDKgdlgdkjgedkjhg', 100);
INSERT INTO PRODUCT VALUES (1005, 'test5', 'kbEBFJKBLKJFELAJF;BEFAJEFJKBHLAKJBF;AFHB;FH;AFH;AHBF;EJFHB;AEWHFKAJHFB;EJHAF;LEHF;LH;FLKHEA;FLHE', 102);
INSERT INTO PRODUCT VALUES (1006, 'test6', 'EFKJHBAEJFKBAWJEBF', 103);
INSERT INTO PRODUCT VALUES (1007, 'test7', 'KJBFEJKBF;JB', 104);
INSERT INTO PRODUCT VALUES (1008, 'test8', 'KJSG;AERLNGSRELKNG', 1000);
INSERT INTO PRODUCT VALUES (1009, 'test9', 'kjrfbgarebg;ajgbhjrsbgh;jrsbgn;jrse', 10);
INSERT INTO PRODUCT VALUES (1010, 'test10', 'wkejfbfajbnklfgnalkjgajgrjagjgja:RJ', 200);
