
--long id
--int numberOfGuests
--double price
--int breakfastIncluded (1 или 0)
--int petsAllowed (1 или 0)
--Date dateAvailableFrom
--Hotel hotel

CREATE TABLE ROOM(
ROOM_ID NUMBER,
CONSTRAINT ROOM_PK PRIMARY KEY(ROOM_ID),
NUMBER_GUESTS NUMBER(20),
PRICE NUMBER (10,2) NOT NULL,
BREAKFAST NUMBER(1) NOT NULL,
CHECK (BREAKFAST BETWEEN 0 AND 1),
PETS NUMBER NOT NULL,
CHECK (PETS BETWEEN 0 AND 1),
DATE_AVAILABLE TIMESTAMP,
HOTEL_ID NUMBER NOT NULL,
CONSTRAINT HOTEL_FK FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL(HOTEL_ID)
);

